name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 298125159991.dkr.ecr.ap-northeast-1.amazonaws.com  # 例: 123456789012.dkr.ecr.us-west-1.amazonaws.com
        ECR_REPOSITORY: ecstest  # 例: my-fastapi-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecstest  # 例: my-fastapi-task
        service: ecs-test-service  # 例: my-fastapi-service
        cluster: ecs-test  # 例: default
        force-new-deployment: true
